# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# languages = [
#   "Afrikaans", "Shqip (Albanian)", "አማርኛ (Amharic)", "العربية (Arabic)", "Հայերեն (Armenian)",
#   "অসমীয়া (Assamese)", "अवधी (Awadhi)", "Azərbaycanca (Azerbaijani)", "Башҡортса (Bashkir)",
#   "Euskara (Basque)", "Беларуская (Belarusian)", "বাংলা (Bengali)", "भोजपुरी (Bhojpuri)",
#   "Bosanski (Bosnian)", "български (Bulgarian)", "မြန်မာဘာသာ (Burmese)", "廣東話 (Cantonese)",
#   "Català (Catalan)", "ᏣᎳᎩ (Cherokee)", "छत्तीसगढ़ी (Chhattisgarhi)", "中文 (Chinese)",
#   "普通话 (Chinese (Simplified))", "Hrvatski (Croatian)", "Čeština (Czech)", "Dansk (Danish)",
#   "डोगरी (Dogri)", "Nederlands (Dutch)", "English", "эрзянь кель (Erzya)", "Esperanto",
#   "Eesti (Estonian)", "Føroyskt (Faroese)", "Filipino", "Suomi (Finnish)", "Français (French)",
#   "Fulfulde (Fula)", "Galego (Galician)", "ქართული (Georgian)", "Deutsch (German)",
#   "Ελληνικά (Greek)", "ગુજરાતી (Gujarati)", "Kreyòl ayisyen (Haitian Creole)", "हरियाणवी (Haryanvi)",
#   "Hausa", "עברית (Hebrew)", "हिन्दी (Hindi)", "Magyar (Hungarian)", "Íslenska (Icelandic)",
#   "Igbo", "Bahasa Indonesia (Indonesian)", "ᐃᓄᒃᑎᑐᑦ (Inuktitut)", "Gaeilge (Irish)",
#   "Italiano (Italian)", "日本語 (Japanese)", "Basa Jawa (Javanese)", "ಕನ್ನಡ (Kannada)",
#   "کشمیری (Kashmiri)", "Қазақ тілі (Kazakh)", "ខ្មែរ (Khmer)", "कोंकणी (Konkani)",
#   "한국어 (Korean)", "Кыргызча (Kyrgyz)", "ລາວ (Lao)", "Latviešu (Latvian)", "Lietuvių (Lithuanian)",
#   "Lëtzebuergesch (Luxembourgish)", "македонски (Macedonian)", "मैथिली (Maithili)", "Malagasy",
#   "Bahasa Melayu (Malay)", "മലയാളം (Malayalam)", "Malti (Maltese)", "मराठी (Marathi)",
#   "मारवाड़ी (Marwari)", "閩南語 (Min Nan)", "Moldovenească (Moldovan)", "Монгол (Mongolian)",
#   "Crnogorski (Montenegrin)", "नेपाली (Nepali)", "Norsk (Norwegian)", "Norsk bokmål (Norwegian (Bokmål))",
#   "ଓଡ଼ିଆ (Oriya)", "پښتو (Pashto)", "فارسی (Persian)", "Polski (Polish)", "Português (Portuguese)",
#   "ਪੰਜਾਬੀ (Punjabi)", "राजस्थानी (Rajasthani)", "Română (Romanian)", "Русский (Russian)",
#   "संस्कृतम् (Sanskrit)", "ᱥᱟᱱᱛᱟᱲᱤ (Santali)", "Српски (Serbian)", "سنڌي (Sindhi)",
#   "සිංහල (Sinhala)", "Slovenčina (Slovak)", "Slovenščina (Slovenian)", "Soomaali (Somali)",
#   "Español (Spanish)", "Kiswahili (Swahili)", "Svenska (Swedish)", "Tagalog", "தமிழ் (Tamil)",
#   "తెలుగు (Telugu)", "ไทย (Thai)", "ትግርኛ (Tigrinya)", "Türkçe (Turkish)", "Українська (Ukrainian)",
#   "اردو (Urdu)", "Oʻzbekcha (Uzbek)", "Tiếng Việt (Vietnamese)", "Cymraeg (Welsh)", "吴语 (Wu)",
#   "isiXhosa (Xhosa)", "Yorùbá (Yoruba)", "isiZulu (Zulu)",
# ]

# languages.each do |name|
#   Language.find_or_create_by!(name: name)
# end

languages = [
  { name: "Afrikaans", iso_code: "af" },
  { name: "Shqip (Albanian)", iso_code: "sq" },
  { name: "አማርኛ (Amharic)", iso_code: "am" },
  { name: "Arabic", iso_code: "ar" },
  { name: "Հայերեն (Armenian)", iso_code: "hy" },
  { name: "অসমীয়া (Assamese)", iso_code: "as" },
  { name: "अवधी (Awadhi)", iso_code: nil },
  { name: "Azərbaycanca (Azerbaijani)", iso_code: "az" },
  { name: "Башҡортса (Bashkir)", iso_code: "ba" },
  { name: "Euskara (Basque)", iso_code: "eu" },
  { name: "Беларуская (Belarusian)", iso_code: "be" },
  { name: "বাংলা (Bengali)", iso_code: "bn" },
  { name: "भोजपुरी (Bhojpuri)", iso_code: "bho" },
  { name: "Bosanski (Bosnian)", iso_code: "bs" },
  { name: "български (Bulgarian)", iso_code: "bg" },
  { name: "မြန်မာစာ (Burmese)", iso_code: "my" },
  { name: "廣東話 (Cantonese)", iso_code: "yue" },
  { name: "Català (Catalan)", iso_code: "ca" },
  { name: "ᏣᎳᎩ (Cherokee)", iso_code: nil },
  { name: "छत्तीसगढ़ी (Chhattisgarhi)", iso_code: nil },
  { name: "中文 (Chinese)", iso_code: "zh" },
  { name: "Chinese (Simplified)", iso_code: "zh" },
  { name: "Hrvatski (Croatian)", iso_code: "hr" },
  { name: "Čeština (Czech)", iso_code: "cs" },
  { name: "Dansk (Danish)", iso_code: "da" },
  { name: "Dogri", iso_code: "doi" },
  { name: "Nederlands (Dutch)", iso_code: "nl" },
  { name: "English", iso_code: "en" },
  { name: "эрзянь кель (Erzya)", iso_code: nil },
  { name: "Esperanto", iso_code: "eo" },
  { name: "Eesti (Estonian)", iso_code: "et" },
  { name: "Føroyskt (Faroese)", iso_code: "fo" },
  { name: "Filipino", iso_code: "fil" },
  { name: "Suomi (Finnish)", iso_code: "fi" },
  { name: "Français (French)", iso_code: "fr" },
  { name: "Fulfulde (Fula)", iso_code: "ff" },
  { name: "Galego (Galician)", iso_code: "gl" },
  { name: "ქართული (Georgian)", iso_code: "ka" },
  { name: "Deutsch (German)", iso_code: "de" },
  { name: "Ελληνικά (Greek)", iso_code: "el" },
  { name: "ગુજરાતી (Gujarati)", iso_code: "gu" },
  { name: "Kreyòl ayisyen (Haitian Creole)", iso_code: "ht" },
  { name: "हरियाणवी (Haryanvi)", iso_code: nil },
  { name: "Hausa", iso_code: "ha" },
  { name: "עברית (Hebrew)", iso_code: "he" },
  { name: "हिन्दी (Hindi)", iso_code: "hi" },
  { name: "Magyar (Hungarian)", iso_code: "hu" },
  { name: "Íslenska (Icelandic)", iso_code: "is" },
  { name: "Igbo", iso_code: "ig" },
  { name: "Bahasa Indonesia (Indonesian)", iso_code: "id" },
  { name: "ᐃᓄᒃᑎᑐᑦ (Inuktitut)", iso_code: "iu" },
  { name: "Gaeilge (Irish)", iso_code: "ga" },
  { name: "Italiano (Italian)", iso_code: "it" },
  { name: "日本語 (Japanese)", iso_code: "ja" },
  { name: "Basa Jawa (Javanese)", iso_code: "jv" },
  { name: "ಕನ್ನಡ (Kannada)", iso_code: "kn" },
  { name: "كشميري (Kashmiri)", iso_code: "ks" },
  { name: "Қазақ тілі (Kazakh)", iso_code: "kk" },
  { name: "ភាសាខ្មែរ (Khmer)", iso_code: "km" },
  { name: "कोंकणी (Konkani)", iso_code: "kok" },
  { name: "한국어 (Korean)", iso_code: "ko" },
  { name: "Кыргызча (Kyrgyz)", iso_code: "ky" },
  { name: "ລາວ (Lao)", iso_code: "lo" },
  { name: "Latviešu (Latvian)", iso_code: "lv" },
  { name: "Lietuvių (Lithuanian)", iso_code: "lt" },
  { name: "Lëtzebuergesch (Luxembourgish)", iso_code: "lb" },
  { name: "македонски (Macedonian)", iso_code: "mk" },
  { name: "मैथिली (Maithili)", iso_code: "mai" },
  { name: "Malay", iso_code: "ms" },
  { name: "മലയാളം (Malayalam)", iso_code: "ml" },
  { name: "Malti (Maltese)", iso_code: "mt" },
  { name: "मराठी (Marathi)", iso_code: "mr" },
  { name: "मारवाड़ी (Marwari)", iso_code: nil },
  { name: "閩南語 (Min Nan)", iso_code: nil },
  { name: "Moldovenească (Moldovan)", iso_code: nil },
  { name: "Монгол (Mongolian)", iso_code: "mn" },
  { name: "Montenegrin", iso_code: nil },
  { name: "नेपाली (Nepali)", iso_code: "ne" },
  { name: "Norsk (Norwegian)", iso_code: "no" },
  { name: "Norsk bokmål (Norwegian Bokmål)", iso_code: "nb" },
  { name: "ଓଡ଼ିଆ (Oriya)", iso_code: "or" },
  { name: "پښتو (Pashto)", iso_code: "ps" },
  { name: "فارسی (Persian)", iso_code: "fa" },
  { name: "Polski (Polish)", iso_code: "pl" },
  { name: "Português (Portuguese)", iso_code: "pt" },
  { name: "ਪੰਜਾਬੀ (Punjabi)", iso_code: "pa" },
  { name: "राजस्थानी (Rajasthani)", iso_code: nil },
  { name: "Română (Romanian)", iso_code: "ro" },
  { name: "Русский (Russian)", iso_code: "ru" },
  { name: "संस्कृतम् (Sanskrit)", iso_code: "sa" },
  { name: "ᱥᱟᱱᱛᱟᱲᱤ (Santali)", iso_code: "sat" },
  { name: "Српски (Serbian)", iso_code: "sr" },
  { name: "سنڌي (Sindhi)", iso_code: "sd" },
  { name: "සිංහල (Sinhala)", iso_code: "si" },
  { name: "Slovenčina (Slovak)", iso_code: "sk" },
  { name: "Slovenščina (Slovenian)", iso_code: "sl" },
  { name: "Soomaali (Somali)", iso_code: "so" },
  { name: "Español (Spanish)", iso_code: "es" },
  { name: "Kiswahili (Swahili)", iso_code: "sw" },
  { name: "Svenska (Swedish)", iso_code: "sv" },
  { name: "Tagalog", iso_code: "tl" },
  { name: "தமிழ் (Tamil)", iso_code: "ta" },
  { name: "తెలుగు (Telugu)", iso_code: "te" },
  { name: "ไทย (Thai)", iso_code: "th" },
  { name: "ትግርኛ (Tigrinya)", iso_code: "ti" },
  { name: "Türkçe (Turkish)", iso_code: "tr" },
  { name: "Українська (Ukrainian)", iso_code: "uk" },
  { name: "اردو (Urdu)", iso_code: "ur" },
  { name: "Oʻzbekcha (Uzbek)", iso_code: "uz" },
  { name: "Tiếng Việt (Vietnamese)", iso_code: "vi" },
  { name: "Cymraeg (Welsh)", iso_code: "cy" },
  { name: "吴语 (Wu)", iso_code: nil },
  { name: "isiXhosa (Xhosa)", iso_code: "xh" },
  { name: "Yorùbá (Yoruba)", iso_code: "yo" },
  { name: "isiZulu (Zulu)", iso_code: "zu" },
]

languages.each do |lang|
  language = Language.find_or_initialize_by(name: lang[:name])
  language.iso_code = lang[:iso_code]
  language.save!
end
